theme: jekyll-theme-minimal
title: Svenja Guhr
description: Personal Website of Svenja Guhr
email: svenja.guhr@gmail.com
description: "Personal Website"

url: "https://SvenjaGuhr.github.io" # the base hostname & protocol for your site
github_username: SvenjaGuhr

plugins:
  - jekyll-feed
