Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@SvenjaGuhr 
SvenjaGuhr
/
blog
Public
Code
Issues
Pull requests
7
Actions
Projects
Security
Insights
SvenjaGuhr.github.io/_config.yml
@SvenjaGuhr
SvenjaGuhr new blog
Latest commit d6c0a15 on Nov 10, 2022
 History
 1 contributor
Executable File  36 lines (30 sloc)  1.03 KB

future: true
title: Site of Svenja Guhr
description: Personal website of Svenja Guhr, mainly Computational Literary Studies content
permalink: ':title/'
baseurl: "/SvenjaGuhr.github.io" # the subpath of your site, e.g. /SvenjaGuhr.github.io
url: "svenjaguhr.github.io" 
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: "Svenja Guhr" # add your name
author-img: "img/Novel_suspense.png" # add your photo
about-author: "Phd student (Computational Literary Studies) at Technical University Darmstadt" # add description
social-twitter: "guhr_s" # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: "SvenjaGuhr" # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: "svenjaguhr@gmail.com" # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics
google_analytics: #

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
SvenjaGuhr.github.io/_config.yml at master · SvenjaGuhr/blog
